apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/gogs-repositories"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi