---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gogs-ingress
spec:
  rules:
  - host: gogs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gogs-service
            port:
              number: 3000