apiVersion: v1
kind: ConfigMap
metadata:
  name: gogs-config
data:
  DOMAIN: "10.211.55.40"
  HTTP_PORT: "30000"
  SSH_PORT: "30022"
  EXTERNAL_URL: "http://10.211.55.40:30000"
  DB_HOST: "postgres-service:5432"