apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - name: gogs
        image: 145023097801.dkr.ecr.eu-north-1.amazonaws.com/gogs:cc83be5
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: gogs-config
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-password
        volumeMounts:
        - name: gogs-repositories
          mountPath: /gogs-repositories
      volumes:
      - name: gogs-repositories
        persistentVolumeClaim:
          claimName: gogs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gogs-service
spec:
  selector:
    app: gogs
  ports:
    - name: http
      port: 80
      targetPort: 3000
